### ISSUE TITLE
failed workflow catcher

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity-os/plugins-wishlist#21]
See [this](https://github.com/ubiquity/pay.ubq.fi/actions/runs/9472156534/job/26097027405?pr=246) workflow run regarding `Build` CI failing during the `yarn` step. I've came across this in testing plugin workflows where the workflow fails for reasons out of user control during a step it shouldn't such as `yarn`.

It's reasonable to expect this to happen again for plugin workflows and the kernel wouldn't know the wf has failed (afaik)

<hr/>

Events to work with below, I think it's possible to track workflow steps by name that fail that are expected to never fail. If so, it would be a beneficial plugin to have that can automatically refire these runs.

```yml
workflow_dispatch: [],
workflow_job: [],
'workflow_job.completed': [],
'workflow_job.in_progress': [],
'workflow_job.queued': [],
'workflow_job.waiting': [],
workflow_run: [],
'workflow_run.completed': [],
'workflow_run.in_progress': [],
'workflow_run.requested': []
```

<hr/>

I feel I lack the insight to properly define the spec for this one, if it is possible at all given the kernel structure.
