### ISSUE TITLE
Autoresponder Plugin (for DevPool Directory)

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os/plugins-wishlist#44]
When any comments are posted, automatically reply with a configurable message. I think the default can be something instructional like "You must set the default auto response in the configuration."

The intended use case is to guide users who mistakenly try and self assign directly on the directory:

> When I just started contributing I made [this same mistake](https://github.com/ubiquity/devpool-directory/issues/1402) and it was never picked up by the team.
> 
> It would be great if we could have an automatic response from the bot when someone comments on any issue in the `devpool-directory`. This message would be something like `This is a no-reply repo, please visit ${taskUrl} to contribute towards this task.`
> 
> We should automate this so that we can set-and-forget which is the best way to handle this.

Originally posted by @Keyrxng https://github.com/ubiquity/devpool-directory-bounties/issues/36

**Comment by Keyrxng** [comment]
I've built the plugin, could a repo be created for me to PR against? @gentlementlegen @0x4007 cheers

```yml
plugins:
  - uses:
      - plugin: http://localhost:4000
        with:
          automatedResponses:
            "auto-responder": "This is a no-reply repo, please visit the link in the issue description. Thank you!"
```

https://github.com/ubq-testing/auto-responder

![Image](https://github.com/user-attachments/assets/aa1ed957-c6dd-4b39-b6e3-ec9cab0865d4)
